In [ ]:
# Importing all the necessary libraries and packages


import pandas as pd
from sklearn.neural_network import MLPClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.model_selection import train_test_split



url = "https://raw.githubusercontent.com/Audry300/Employee-Satisfaction-prediction/main/Employee%20Satisfaction%20Index.csv"

employeesData = pd.read_csv(url).drop(['emp_id'],axis=1)
employeesData.drop(employeesData.columns[0],axis=1,inplace=True)

employeesData.head(10)




# Preparing the data


bins_salary = [0, 30000, 50000, 100000]
salary_ranges= ['low_salary', 'average_salary','top_salary']
employeesData['salary'] = pd.cut(employeesData['salary'], bins=bins_salary, labels=salary_ranges)
employeesData['salary'].unique()

bins_age=[0,30,45,65]
age_ranges = ['junior_employee','midlevel_employee','senior_employee']
employeesData['age'] = pd.cut(employeesData['age'],bins=bins_age,labels=age_ranges)
employeesData['age'].unique()

bins_rating=[0,2,3.5,5]
rating_ranges = ['low','mid','top']
employeesData['rating']=pd.cut(employeesData['rating'],bins=bins_rating,labels=rating_ranges)
employeesData['rating'].unique()

bins_awards=[-1,3,6,9]
awards_ranges = ['few','average','high']
employeesData['awards']=pd.cut(employeesData['awards'],bins=bins_awards,labels=awards_ranges)
employeesData['awards'].unique()

# Encoding some values

encoder = LabelEncoder()

employeesData['age'] = encoder.fit_transform(employeesData['age'])
employeesData['Dept'] = encoder.fit_transform(employeesData['Dept'])
employeesData['location'] = encoder.fit_transform(employeesData['location'])
employeesData['education'] = encoder.fit_transform(employeesData['education'])
employeesData['recruitment_type'] = encoder.fit_transform(employeesData['recruitment_type'])
employeesData['awards'] = encoder.fit_transform(employeesData['awards'])
employeesData['rating'] = encoder.fit_transform(employeesData['rating'])
employeesData['salary'] = encoder.fit_transform(employeesData['salary'])





# Separating the dataset to extract the value(satisfied) we want to predict from the features

Dataset = employeesData.drop('satisfied',axis=1)
value = employeesData['satisfied']



# Separating the Testing from the Training data

Dataset_train, Dataset_test, value_train, value_test = train_test_split(Dataset,value)



# Scaling the data

sc = StandardScaler()
Dataset_train= sc.fit_transform(Dataset_train)
Dataset_test=sc.transform(Dataset_test)


# Naive Bayes model
print("\n \n NAIVES BAYES RESULTS -----------------------------------\n")

gnb = GaussianNB()
naive_bayes_train = gnb.fit(Dataset_train,value_train)
naives_bayes_prediction = naive_bayes_train.predict(Dataset_test)
print(classification_report(value_test,naives_bayes_prediction))



# MLP
print("\n \n MULTI PERCEPTRONS RESULTS ------------------------------\n")

DataNeuralNetwork = MLPClassifier()
DataNeuralNetwork.fit(Dataset_train,value_train)
DataNeuralNetwork_prediction = DataNeuralNetwork.predict(Dataset_test)
print(classification_report(value_test,DataNeuralNetwork_prediction))


# Logistic Regression
print("\n \n LOGISTIC REGRESSION RESULTS ----------------------------\n")


# Feature Engineering (one hot encoding)
LogisticR = LogisticRegression()
LogisticR.fit(Dataset_train,value_train)
LogisticR_prediction = LogisticR.predict(Dataset_test)
print(classification_report(value_test,LogisticR_prediction))

'''
Dataset = pd.get_dummies(Dataset)
print(Dataset);

LogisticR = LogisticRegression()
LogisticR.fit(DataSet_train,value_train)
LogisticR_prediction = LogisticR.predict(Dataset_test)
print(classification_report(value_test,LogisticR_prediction))
'''








employeesData.head(10)

 NAIVES BAYES RESULTS -----------------------------------

              precision    recall  f1-score   support

           0       0.56      0.32      0.40        57
           1       0.58      0.79      0.67        68

    accuracy                           0.58       125
   macro avg       0.57      0.55      0.54       125
weighted avg       0.57      0.58      0.55       125



 MULTI PERCEPTRONS RESULTS ------------------------------

              precision    recall  f1-score   support

           0       0.59      0.42      0.49        57
           1       0.61      0.75      0.67        68

    accuracy                           0.60       125
   macro avg       0.60      0.59      0.58       125
weighted avg       0.60      0.60      0.59       125



 LOGISTIC REGRESSION RESULTS ----------------------------

              precision    recall  f1-score   support

           0       0.54      0.37      0.44        57
           1       0.58      0.74      0.65        68

    accuracy                           0.57       125
   macro avg       0.56      0.55      0.54       125
weighted avg       0.56      0.57      0.55       125

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,

,age,Dept,location,education,recruitment_type,job_level,rating,onsite,awards,certifications,salary,satisfied
0,0,0,1,0,2,5,0,0,1,0,2,1
1,2,4,1,0,3,3,2,1,1,1,0,0
2,1,4,1,1,2,4,0,0,1,0,2,0
3,1,3,0,0,0,2,1,1,1,0,1,1
4,1,0,0,1,1,2,0,0,0,0,1,1
5,1,2,1,1,2,3,1,0,2,1,0,1
6,0,2,1,1,2,5,2,0,1,0,2,0
7,0,4,0,1,1,1,0,0,0,0,1,0
8,1,0,0,0,2,3,2,0,1,0,0,1
9,1,4,0,0,2,3,1,0,2,0,0,0